services:
    project1:
        volumes:
            - ./apps/project1:/app
            - ./apps/project1/node_modules:/app/node_modules
        build:
            context: ./apps/project1
            dockerfile: docker/dockerfile.dev
        container_name: nest-app
        env_file:
            - ./apps/project1/.env
        ports:
            - '${PROJECT_PORT_1}:3000'
        depends_on:
            - database
        restart: on-failure
    database:
        image: postgres:16
        container_name: postgres-db
        ports:
            - '${POSTGRES_PORT}:5432'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: on-failure

volumes:
    pgdata:
