# 1. Используем официальный образ Node.js
FROM node:22.9.0

# 2. Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# 3. Открываем порт
EXPOSE 3000

# 4. Устанавливаем зависимость для ожидания загрузки БД
RUN apt-get update && apt-get install -y wait-for-it

# 5. Запускаем команду ожидания базы данных и затем приложение
CMD /bin/bash -c "wait-for-it database:5432 -- npm run start:dev"
