services:
    new-project:
        volumes:
            - ..:/app
            - ../node_modules:/app/node_modules
        build:
            context: ..
            dockerfile: docker/dockerfile.prod
        container_name: new-project
        env_file:
            - ../.env.development
        environment:
            - NODE_ENV=development # Указываем переменную окружения для использования нужного .env
        ports:
            - '${PROJECT_PORT}:3000'
        depends_on:
            - new-project_db
        restart: on-failure
    new-project_db:
        image: postgres:16
        container_name: new-project_db
        ports:
            - '${POSTGRES_PORT}:5432'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - new-project_pgdata:/var/lib/postgresql/data
        restart: on-failure

volumes:
    new-project_pgdata:
